version: "3.9"

services:
  silentrace:
    build: .
    container_name: silentrace
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app:/app/app/
      - ./${PATH_TO_MOUT}:/app/app/static/uploads 
    env_file:
      - .env
    stdin_open: true 
    tty: true       

